export enum STATUS_EFFECT {
  NONE = "NONE",
  BURN = "BURN",
  BLEED = "BLEED",
  POISON = "POISON",
  HIDDEN = "HIDDEN",
  SHOCK = "SHOCK",
  ADVANTAGE = "ADVANTAGE",
  DISADVANTAGE = "DISADVANTAGE",
  REGEN = "REGEN",
  SHIELD = "SHIELD",
  HASTE = "HASTE",
  SLOW = "SLOW",
}

export enum STATUS_RATING {
  COMMON = "COMMON",
  UNCOMMON = "UNCOMMON",
  RARE = "RARE",
  LEGENDARY = "LEGENDARY",
}

export const STATUS_EFFECTS: STATUS_EFFECT[] = Object.keys(STATUS_EFFECT).map((key) => (STATUS_EFFECT as any)[key]);

export type ROLL_STATUS = STATUS_EFFECT.ADVANTAGE | STATUS_EFFECT.DISADVANTAGE | STATUS_EFFECT.NONE;

export const ROLL_STATUSES: STATUS_EFFECT[] = [STATUS_EFFECT.ADVANTAGE, STATUS_EFFECT.DISADVANTAGE, STATUS_EFFECT.NONE];
